version: "3"

services:
  miniconda_jupyter_server:
    build: ./
    command: jupyter server --config=./config/jupyter_server_config.py
    restart: unless-stopped
    container_name: opencv_cells_detection
    image: miniconda_jupyter_server 
    ports:
      - "5522:8888"
    volumes: 
      - ../:/usr/src/miniconda_jupyter_server
